---
kind: "operation"
client: "com.atomist:rug"
version: "1.0.0-20170809213747"
editor:
  name: "AddAtomistAgent"
  group: "atomist"
  artifact: "spring-team-handlers"
  version: "0.9.0"
  origin:
    repo: "git@github.com:atomisthq/spring-team-handlers.git"
    branch: "96f76d1fdef8ba89272c97c8490cbd60c18f200d"
    sha: "96f76d1"
  parameters:
    - "slackTeam": "T6AMU844U"

